# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.TextField(default='empty account name', max_length=32),
        ),
        migrations.AddField(
            model_name='charge',
            name='date',
            field=models.DateField(default=datetime.date(2016, 11, 16)),
        ),
    ]
